### ISSUE TITLE
hi~有木有那个美学IQA的paper 呀~

### ISSUE THREAD

**Issue by wrbuaa** [HuiZeng/Unified_IAA#1]
您好，我是BUAA的研一学生，最近在看美学评价方面的东西，查到您的这个unified IAA的代码。。可是没有找到对应的文献。请问您有木有呀~谢谢

**Comment by HuiZeng** [comment]
你好，paper目前还在审稿状态，没有公开，所以暂时不能提供，抱歉。

2018-05-29 10:32 GMT+08:00 wrbuaa <notifications@github.com>:

**Comment by zwx8981** [comment]
Hi~请问这篇美学的paper录用了吗，很感兴趣！

**Comment by HuiZeng** [comment]
> Hi~请问这篇美学的paper录用了吗，很感兴趣！

你好，还没有，审稿周期实在太长了 :(

**Comment by HuiZeng** [comment]
> Hi~请问这篇美学的paper录用了吗，很感兴趣！

论文已经录用了，现在可以看到了。不过拖了整整两年了，实效性可能比较一般了。

**Comment by zwx8981** [comment]
哈哈恭喜恭喜，我觉得不会过时，这个方向的开源代码本身就很少，要是能有pytorch版一定能火。

**Comment by HuiZeng** [comment]
> 哈哈恭喜恭喜，我觉得不会过时，这个方向的开源代码本身就很少，要是能有pytorch版一定能火。

这个方向我已经不做很久了，应该不会再花时间整理pytorch版本的代码了。
