### ISSUE TITLE
Request for the test code.

### ISSUE THREAD

**Issue by codeslake** [HuiZeng/Unified_IAA#2]
It seems like you only provide the training code.
Is it possible for you to release the test code?

**Comment by HuiZeng** [comment]
Hi, the test codes are in the folder "tools/src"

**Comment by codeslake** [comment]
Thanks for the response!
Is the checkpoint in the readme the trained for the assessment? or is it trained for the imagenet classification?

**Comment by HuiZeng** [comment]
For imagenet classification.

**Comment by codeslake** [comment]
Will it be possible for you to share the checkpoint for the assessment?

**Comment by HuiZeng** [comment]
This work has been finished by three years, which is too long for me to remember all details. 
Retraining a new model costs about 1 day if I remember correctly.

**Comment by codeslake** [comment]
Alright, thanks for your response :)
